### PR TITLE
Fix #88 Breaks with mini-css-extract-plugin@1.3.0

### LINKED ISSUE #88: Breaks with mini-css-extract-plugin@1.3.0
Webpack build fails when using both mini-css-extract-plugin@1.3.0 and external-svg-sprite-loader.

I created a repo with repro: https://github.com/mihkeleidast/webpack-css-svg-issue

I originally reported this to mini-css-extract-plugin but I was told this should be fixed here: https://github.com/webpack-contrib/mini-css-extract-plugin/issues/653

### PR DESCRIPTION
**Pull request by bensampaio**
* Convert the `CssModule` content to string in order to be able to replace the Sprite URL.
* Convert the `CssModule` content back to `Buffer` if it was a buffer before so that the plugin remains compatible with older versions of `CssModule`.
* Change from `[hash]` to `[contenthash]` since this is now the recommended way of generating hashes and because this should also result in less filename changes.
* Update the `react` example installation so that it uses hashes in order to no longer cache assets.

### CODE REVIEW

File: lib/SvgStorePlugin.js [hunk 1]
```diff
@@ -200,9 +200,15 @@ class SvgStorePlugin {
      */
     replaceSpritePathsInModuleWithInterpolatedPaths(module, sprite) {
         switch (module.constructor.name) {
-            case 'CssModule':
-                module.content = sprite.replacePathsWithInterpolatedPaths(module.content);
+            case 'CssModule': {
+                const content = sprite.replacePathsWithInterpolatedPaths(module.content.toString());
+
+                if (Buffer.isBuffer(module.content)) {
```
Comment (mihkeleidast) [inline lib/SvgStorePlugin.js:206]: Shouldn't there be an `else if (typeof module.content === 'string')` here? I'm guessing the update would break those using an older version of mini-css-extract-plugin? I don't use this SVG path in CSS myself but just noticed it...

Comment (bensampaio) [reply lib/SvgStorePlugin.js]: You are right, thanks for checking! That was my intention and then I ended up doing it wrong 😅 

Should be fixed now.

Comment (bensampaio) [reply lib/SvgStorePlugin.js]: I released it as 7.1.0-beta.2. Can you let me know if this still works for you just as a sanity check?

Comment (mihkeleidast) [reply lib/SvgStorePlugin.js]: Looks like it works in my repro repository.

Comment (bensampaio) [reply lib/SvgStorePlugin.js]: Thanks! I'll merge it and release it as 7.1.0 then :)
