### PR TITLE
Moved defs to top for FF & gradient ids no longer clash. Fixes #26

### LINKED ISSUE #26: LinearGradients don't work inside symbol on Firefox
The sprite wraps the linearGradient of an svg inside the symbol which does not work on Firefox. It should set it inside the svg tags and reference inside the symbol.

### PR DESCRIPTION
**Pull request by stowball**
Since minification was happening first, all gradients were being assigned an `id` of `a` to `z`, so all SVGs were using the first gradient `id` and not there own. Prefixing the `id`s solves that.

Also concatenated and moved any `<defs>` references to the top of the SVG so Firefox renders them correctly

### CODE REVIEW

File: lib/SvgDocument.js [hunk 1]
```diff
@@ -150,7 +160,7 @@ class SvgDocument {
             }
         });
 
-        return SvgDocument.createSymbol(attrs, $svg.html());
+        return SvgDocument.createSymbol(attrs, $svg.html().replace(/( id="|"url\(#)/g, `$1${id}`));
```
Comment (bensampaio) [inline lib/SvgDocument.js]: @stowball can you move `$svg.html().replace(/( id="|"url\(#)/g, `$1${id}`)` into a different line and leave a comment explaining what's happening here and why it is necessary?

File: lib/SvgDocument.js [hunk 2]
```diff
@@ -26,7 +26,17 @@ class SvgDocument {
      * @returns {string}
      */
     static create(...contents) {
```
Comment (bensampaio) [inline lib/SvgDocument.js]: @stowball I would like to keep this file sprite ignorant. This function should be only about creating an SVG document with the given contents. So it should stay as it was before and the `defs` logic should go somewhere else. Couldn't we maybe already remove the `defs` from the symbol in the `toSymbol` method and then have a method to extract `defs` from an SVG file (something like `SvgDocument.extractDefs`)? Then in the `SvgSprite.generate` method we could have a list of defs which receives the extracted defs. And the line `SvgDocument.createDefs(...symbols)` would instead be `SvgDocument.createDefs(...defs, ...symbols)`. What do you think?

Comment (stowball) [inline lib/SvgDocument.js]: Ah sorry, I agree that this probably isn't the right place to do it for your plugin but I didn't even see `createDefs` because I first made the change [in my simpler fork](https://github.com/stowball/webpack-svg-icon-system/) which removed a lot of the original code and then just copied and pasted.

Unfortunately, there's a bit too much involved for me to take this on at the moment as the current final output seems a bit weird to me as well:

```
// Generate the sprite content with the following format:
// <svg>
//   <defs>
//       ...<symbol />
//   </defs>
//   ...<view />
//   ...<use />
// </svg>
```

I'm more than happy for you to take over if you like.

**Comment by bensampaio** [comment]
@stowball thanks for sharing! Do you have a SVG with clipPath's that I could use for testing? I think I could fix that very easily.

**Comment by stowball** [comment]
@bensampaio See the addition to my original comment

**Comment by bensampaio** [comment]
@stowball thanks!
